### PR TITLE
XML refactor

### PR DESCRIPTION
**Pull request by Exund**
Refactor XML import/export to use less memory

### CODE REVIEW

**Comment by Exund** [comment]
Currently only the export logic has been changed.

**Comment by IGNRexI** [comment]
I'm getting playerglobal.swc error during installation, please help. and can't find debug code edit.

image

**Comment by jindrapetrik** [comment]
> I'm getting playerglobal.swc error during installation, please help. and can't find debug code edit.
> 
> image

Please, just uncheck "download playerglobal.swc" during installation when there's page with checkboxes what to install.

**Comment by jindrapetrik** [comment]
@Exund Thank you very much for your contribution. Sorry for the long delay before merging, I was busy. Also the problem with missing playerglobal.swc on adobe website blocked the nightly releases for a long time.

**Pull request merged**
