### PR TITLE
Modernize ffdec.sh executable

### PR DESCRIPTION
**Pull request by RedstoneWizard08**
Just allows the ffdec.sh file to be more accessible. Currently only works with OpenJDK, but I'm working on a fix.

### CODE REVIEW

**Review by Newbytee — COMMENTED** [review]
How does this make the script "more accessible"? What are the tangible benefits of this refactoring?

**Comment by RedstoneWizard08** [comment]
The original one didn't work on ARM-based architectures, so I decided to fix it. I also fixed a few bugs involving the find/replace operations to allow for better compatibility.

**Comment by Newbytee** [comment]
> The original one didn't work on ARM-based architectures, so I decided to fix it. I also fixed a few bugs involving the find/replace operations to allow for better compatibility.

I think it would be good if you explicitly mentioned this in your rationale for this change. However, I have no problems running the JPEXS Decompiler Flatpak package from Flathub on 64-bit ARM. How are you reproducing your issue exactly?

**Comment by jindrapetrik** [comment]
Sorry, I need to close this. Please create new PR if you finish it and merge with current version.
I need to keep having number of PRs zero because some dull users (not meaning you) keep creating new PRs for feature requests and/or bug requests without any code to push :-(. With PR count 0, they will not have the urge to click Create new PR button I guess (and will use proper way - the issue tracker).

**Pull request closed without merging**
