### PR TITLE
Add appstream metadata

### PR DESCRIPTION
**Pull request by Newbytee**
This is mandatory for the package to be available on Flathub. However, one thing is missing: screenshots! I'm not sure where I should get one (it can be a link). Suggestions?

### CODE REVIEW

**Comment by jindrapetrik** [comment]
I've got some screenshots from older versions, but they are not well up-to date. I will make some new, more representative, stay tuned...

**Comment by jindrapetrik** [comment]
You can now find some screenshots of the current (stable) version in [graphics/screenshots/version14.4.0](https://github.com/jindrapetrik/jpexs-decompiler/tree/dev/graphics/screenshots/version14.4.0) folder. On one level up you can find screenshots from older versions, but these probably won't be needed.

**Comment by Newbytee** [comment]
> You can now find some screenshots of the current (stable) version in [graphics/screenshots/version14.4.0](https://github.com/jindrapetrik/jpexs-decompiler/tree/dev/graphics/screenshots/version14.4.0) folder. On one level up you can find screenshots from older versions, but these probably won't be needed.

Nitpick: You have two 09 and no 08. I assume one of them should be renamed to 08?

**Comment by Newbytee** [comment]
You are very welcome to review the captions I gave the screenshots. I'm not super familiar with Flash or this decompiler, so I may have been needlessly vague in some cases. There shouldn't be anything incorrect though.

**Comment by jindrapetrik** [comment]
Okay, I reviewed and changed the captions a bit. I also changed the wrong ordering of the filenames. Now what?

**Comment by Newbytee** [comment]
> Now what?

Should be fine to merge! You may or may not want to include this in the build script for making the deb file, but I don't have a system to test whether it works properly for that (I don't use Ubuntu or Debian).

**Pull request closed without merging**
