### PR TITLE
ShapeExporter bug when zoom != 1

### PR DESCRIPTION
**Pull request by dilshod**

### CODE REVIEW

**Comment by honfika** [comment]
Thanks, I modified it a little bit, please check it:
https://github.com/jindrapetrik/jpexs-decompiler/commit/5ccbc424f607fb6c6eb4cdfcc677a816f1bdc61f?w=0

**Comment by dilshod** [comment]
I have a very strange behaviour,

                import com.jpexs.decompiler.flash.exporters.commonshape.Matrix;
                
                Matrix m = new Matrix();
                m.scale(5);
                m.translate(100.0, 100.0);
                
                System.out.println(m.translateX);
                System.out.println(m.translateY);

I get 100, 100 in output, it should be 500, 500.
And it works correct if i replace m.translate with:

                m.translateX = m.scaleX * 100 + m.rotateSkew1 * 100 + m.translateX;
                m.translateY = m.rotateSkew0 * 100 + m.scaleY * 100 + m.translateY;

Because of this your change is not working for me.
Very strange.

**Comment by honfika** [comment]
for me it outputs 500, 500
Did you try to rebuild the project?

**Comment by dilshod** [comment]
I'm using ffdec_8.0.1_nightly1461_lib.jar

**Comment by honfika** [comment]
But the fix is in 1462:)

**Comment by dilshod** [comment]
I'm using custom code for shape exporting. I'll try 1462 too.

**Comment by dilshod** [comment]
I just updated library to 1462, and removed 8.0.1_lib.jar, and everything is good now.
Thanks

**Pull request closed without merging**
