### PR TITLE
As3 vector literal parsing fix

### PR DESCRIPTION
**Pull request by EnricoZeilmaker**
Fixes AS3 vector literals giving broken AVM2 instructions when they have elements.
This changes the AVM2 instructions for vector literal to be in line with what mxmlc produces

and removing some junk files and updating .gitignore

### CODE REVIEW

**Comment by jindrapetrik** [comment]
Could you explain more how it "breaks AVM2 instructions when they have elements"?

It looks like the previous version emmits findproperty and then getproperty, which should be the same as getlex.
(some compilers prefer getlex, other use the two instructions)

Or is there another problem?

**Comment by EnricoZeilmaker** [comment]
If it does the same as getlex, I am not exactly sure what the problem is. 

When I run [this file using the current way](https://drive.google.com/file/d/16lHcsw8F5QUgbj2TZ42naEB4U4rXwSl2/view?usp=sharing), it doesn't work, but when I run [this same file but using getlex](https://drive.google.com/file/d/1SoUyOJB1ZJTJ9_MW2Q_T1T5Gfx1zcRwb/view?usp=sharing) it runs fine

**Comment by RealPuzzlecube** [comment]
this appears to be what a debug projector shows the error to be in the getproperty variant

image

**Comment by RealPuzzlecube** [comment]
ah, the issue was the use of a Multiname as opposed to a QName, not getproperty itself. [Here is the fixed getproperty variant](https://drive.google.com/file/d/1PGELF9gHAprHlwlqYO5dUuCDbbussITK/view?usp=drive_link)

**Comment by jindrapetrik** [comment]
The problem here is that the Multiname does not have "__AS3__.vec" in its namespace set. Adding that namespace in the namespace set will be hard at this point in the InitVectorAVM2Item class, so I decided to integrate your solution with the getlex,
I merge this...

**Pull request merged**
