### PR TITLE
Insert tag (add tag before/after another tag)

### PR DESCRIPTION
**Pull request by Exund**

### CODE REVIEW

**Comment by jindrapetrik** [comment]
Thanks, looks cool.
It conflicted with my new feature - set tag position inside locales so I added a fix commit.

One note:
It would make sense to allow adding other tag types with this feature other than what's category is it in.
For example if you rightclick defineshape, you may want to add definebitsjpeg before this tag to make use it as its fill texture.

Current FFDec does not display actual tag order (not couting Dump view),
but it is important.

But the menu would be too large if it contained all tag types. So it might be categorized into submenus.
I will implement this addition if you don't mind...

Let me know when this is ready to merge (it's still marked as draft).

**Comment by Exund** [comment]
I still have to test stuff to be sure
It behaves a bit weirdly in the UI with frames due to them not actually being data structures in a SWF
I'll perhaps limit the tags that can be added before/after frames to ShowFrameTag

**Comment by jindrapetrik** [comment]
I did a lot of changes in contextmenu regarding new feature - tag list view and it produced some conflicts in your branch.
I commited the conflicts fix to your branch.

I hope it can be moved from Draft stage soon, since it may produce future conflicts if not merged.

**Comment by jindrapetrik** [comment]
Sorry, but I refactored the context menu again.
So I commited conflicts fixing.
It could be really mess integrating these commits into your new work, sorry :-(.
I hope it can be merged soon.

**Comment by Exund** [comment]
For the sake of simplicity let's merge it
From what I've tested it works and the frames problem can be fixed later easily without causing conflicts

**Comment by jindrapetrik** [comment]
Thank you.

**Pull request merged**
